services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testorchestra_results
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/startup.sql:/docker-entrypoint-initdb.d/startup.sql

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
