
-- TestOrchestra - Initiales PostgreSQL-Schema

CREATE TABLE IF NOT EXISTS test_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    duration_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_run_id BIGINT NOT NULL REFERENCES test_runs(id)
        ON DELETE CASCADE,
    name TEXT NOT NULL,
    uri TEXT,
    status TEXT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id BIGINT NOT NULL REFERENCES features(id)
        ON DELETE CASCADE,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES scenarios(id)
        ON DELETE CASCADE,
    keyword TEXT NOT NULL,
    text TEXT NOT NULL,
    status TEXT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    error TEXT
);

CREATE TABLE IF NOT EXISTS scenario_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES scenarios(id)
        ON DELETE CASCADE,
    tag TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_features_test_run_id
    ON features(test_run_id);

CREATE INDEX IF NOT EXISTS idx_scenarios_feature_id
    ON scenarios(feature_id);

CREATE INDEX IF NOT EXISTS idx_steps_scenario_id
    ON steps(scenario_id);

CREATE INDEX IF NOT EXISTS idx_scenario_tags_scenario_id
    ON scenario_tags(scenario_id);
