import * as fs from "fs";
import * as path from "path";

type StepResult = {
  keyword: string;
  text: string;
  status?: string;
  duration_ms?: number;
  error?: string;
};

type ScenarioResult = {
  name: string;
  status?: string;
  duration_ms?: number;
  steps?: StepResult[];
  tags?: string[];
};

type FeatureResult = {
  name: string;
  scenarios?: ScenarioResult[];
};

type TestRunResult = {
  features?: FeatureResult[];
  started_at?: string;
  finished_at?: string;
};

type FlattenedScenario = ScenarioResult & {
  featureName: string;
};

type XrayStepResult = {
  status: "PASSED" | "FAILED" | "TODO";
  comment: string;
  actualResult?: string;
};

type XrayTestResult = {
  testKey?: string;
  testInfo?: {
    projectKey: string;
    summary: string;
    type: "Manual" | "Generic";
  };
  start: string;
  finish: string;
  status: "PASSED" | "FAILED" | "TODO";
  comment: string;
  steps: XrayStepResult[];
};

type XrayJsonReport = {
  info: {
    project: string;
    summary: string;
    description: string;
    startDate: string;
    finishDate: string;
    testEnvironments?: string[];
  };
  tests: XrayTestResult[];
};

export class XrayJsonExporter {
  async export(result: TestRunResult): Promise<void> {
    const reportDir = "reports";
    const reportPath = path.join(reportDir, "xray-report.json");

    fs.mkdirSync(reportDir, { recursive: true });

    const now = new Date().toISOString();
    const scenarios = this.flattenScenarios(result);

    const report: XrayJsonReport = {
      info: {
        project: process.env.XRAY_PROJECT_KEY ?? "QTO",
        summary: this.buildExecutionSummary(),
        description: "Automatically generated by TestOrchestra",
        startDate: result.started_at ?? now,
        finishDate: result.finished_at ?? now,
        testEnvironments: [process.env.TEST_ENVIRONMENT ?? "local"]
      },
      tests: scenarios.map(scenario => this.renderTest(scenario, now))
    };

    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2), "utf8");

    console.log(`📄 Xray JSON report written to ${reportPath}`);
  }

  private flattenScenarios(result: TestRunResult): FlattenedScenario[] {
    return (
      result.features?.flatMap(feature =>
        (feature.scenarios ?? []).map(scenario => ({
          featureName: feature.name,
          ...scenario
        }))
      ) ?? []
    );
  }

  private renderTest(scenario: FlattenedScenario, fallbackTime: string): XrayTestResult {
    const xrayTestKey = this.extractXrayTestKey(scenario.tags ?? []);

    const base: XrayTestResult = {
      start: fallbackTime,
      finish: fallbackTime,
      status: this.mapStatus(scenario.status),
      comment: this.buildScenarioComment(scenario),
      steps: (scenario.steps ?? []).map(step => this.renderStep(step))
    };

    if (xrayTestKey) {
      return {
        ...base,
        testKey: xrayTestKey
      };
    }

    return {
      ...base,
      testInfo: {
        projectKey: process.env.XRAY_PROJECT_KEY ?? "QTO",
        summary: scenario.name,
        type: "Manual"
      }
    };
  }

  private renderStep(step: StepResult): XrayStepResult {
    const status = this.mapStatus(step.status);

    const result: XrayStepResult = {
      status,
      comment: `${step.keyword} ${step.text}`
    };

    if (step.error) {
      result.actualResult = this.sanitize(step.error);
    }

    return result;
  }

  private mapStatus(status?: string): "PASSED" | "FAILED" | "TODO" {
    if (status === "passed") {
      return "PASSED";
    }

    if (status === "failed") {
      return "FAILED";
    }

    return "TODO";
  }

  private extractXrayTestKey(tags: string[]): string | undefined {
    return tags.find(tag => /^[A-Z][A-Z0-9]+-\d+$/.test(tag.replace(/^@/, "")))?.replace(/^@/, "");
  }

  private buildExecutionSummary(): string {
    const runNumber = process.env.GITHUB_RUN_NUMBER;
    const date = new Date().toISOString().slice(0, 10);

    if (runNumber) {
      return `Nightly Test #${runNumber} - ${date}`;
    }

    return `TestOrchestra Run - ${date}`;
  }

  private buildScenarioComment(scenario: FlattenedScenario): string {
    return [
      `Feature: ${scenario.featureName}`,
      `Scenario: ${scenario.name}`,
      `Status: ${scenario.status ?? "unknown"}`,
      `Duration: ${scenario.duration_ms ?? 0} ms`
    ].join("\n");
  }

  private sanitize(value: string): string {
    return value.replace(/\u001b\[[0-9;]*m/g, "");
  }
}