name: Nightly Run

on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

permissions:
  contents: read
  actions: read
jobs:
  nightly-test:
    uses: ./.github/workflows/test-run.yaml
    with:
      report: robot

    secrets: inherit
    permissions:
      contents: read
      actions: read

  upload-xray:
    needs: nightly-test
    runs-on: ubuntu-latest

    env:
      XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
      XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
      XRAY_PROJECT_KEY: QTO

    steps:
      - name: Download Robot XML report
        uses: actions/download-artifact@v4
        with:
          name: testorchestra-robot-report
          path: reports

      - name: Upload Xray JSON report to Xray
        run: |
          TOKEN=$(curl -s \
          -H "Content-Type: application/json" \
          -X POST \
          --data "{\"client_id\":\"$XRAY_CLIENT_ID\",\"client_secret\":\"$XRAY_CLIENT_SECRET\"}" \
          https://eu.xray.cloud.getxray.app/api/v2/authenticate | tr -d '"')

          DATE=$(date +%F)

          cat > test-execution.json <<EOF
          {
          "fields": {
          "project": {
          "key": "QTO"
          },
          "summary": "Robot Adapter Test - ${DATE}",
          "description": "Robot-compatible XML generated by TestOrchestra",
          "issuetype": {
            "name": "Test Execution"
          },
          "assignee": {
            "accountId": "712020:57db405f-4d18-4b41-bbe5-cd33570450c8"
          },
          "labels": [
            "robot",
            "testorchestra"
            ]
          }
          }
          EOF

          curl -s \
          -o robot-response.json \
          -w "%{http_code}" \
          -H "Authorization: Bearer $TOKEN" \
          -F "results=@reports/robot-output.xml;type=text/xml" \
          -F "info=@test-execution.json;type=application/json" \
          https://eu.xray.cloud.getxray.app/api/v2/import/execution/robot/multipart

          cat robot-response.json
