name: Nightly Run

on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

permissions:
  contents: read
  actions: read
jobs:
  nightly-test:
    uses: ./.github/workflows/test-run.yaml
    with:
      report: robot

    secrets: inherit
    permissions:
      contents: read
      actions: read

  upload-xray:
    needs: nightly-test
    runs-on: ubuntu-latest

    env:
      XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
      XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
      XRAY_PROJECT_KEY: QTO

    steps:
      - name: Download Robot reports
        uses: actions/download-artifact@v8
        with:
          pattern: testorchestra-*-robot-report
          path: reports
